apiVersion: v2
appVersion: "15.0"
dependencies:
- condition: postgresql.enabled,
  name: postgresql
  repository: file://../postgresql
  version: 10.16.x
- condition: redis.enabled,
  name: redis
  repository: file://../redis
  version: 15.7.x
description: Odoo chart for Kubernetes using Tecnativa's Docker odoo base (Doodba)
icon: https://odoocdn.com/openerp_website/static/src/img/assets/png/odoo_logo.png?a=b
keywords:
- odoo
- doodba
maintainers:
- email: pca@pledra.com
  name: Paul Catinean
  url: http://pledra.com
name: odoo-doodba
version: 2.0.9
